# Generated by Django 4.2 on 2023-04-17 04:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Imgs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgs', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Katalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=225)),
                ('discrpition', models.CharField(max_length=225)),
                ('img_url', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Main_contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(max_length=252)),
                ('menejer', models.CharField(max_length=252)),
                ('mebel_menejer', models.CharField(max_length=252)),
                ('guarantee', models.IntegerField(default=0)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ManiImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Prodouct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=225)),
                ('discrpition', models.CharField(max_length=225)),
                ('img_url', models.ImageField(upload_to='')),
                ('price', models.IntegerField()),
                ('like', models.BooleanField(default=False)),
                ('carts', models.BooleanField(default=False)),
                ('color', models.TextField(max_length=25)),
                ('manufacturer', models.TextField(max_length=25)),
                ('material', models.TextField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=225)),
                ('discrpition', models.CharField(max_length=225)),
                ('video_url', models.TextField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Prodouct_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('img_url', models.ImageField(upload_to='')),
                ('katalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dafna_app.katalog')),
            ],
        ),
        migrations.CreateModel(
            name='Prodouct_img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('prodouct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dafna_app.prodouct')),
            ],
        ),
        migrations.AddField(
            model_name='prodouct',
            name='prodouct_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dafna_app.prodouct_type'),
        ),
        migrations.CreateModel(
            name='Love',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodouct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dafna_app.prodouct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branches_name', models.CharField(max_length=252)),
                ('address', models.CharField(max_length=252)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('menefer', models.CharField(max_length=252)),
                ('main_contacts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dafna_app.main_contacts')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodouct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dafna_app.prodouct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
