# Generated by Django 4.1.7 on 2023-02-18 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dafna_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodouct',
            name='img_url',
            field=models.TextField(default='nada', max_length=225),
            preserve_default=False,
        ),
    ]
