# Generated by Django 4.1.7 on 2023-02-18 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dafna_app', '0002_prodouct_img_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='love',
            old_name='score',
            new_name='prodouct',
        ),
    ]
