# Generated by Django 4.1.7 on 2023-02-20 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dafna_app', '0002_alter_contact_address_alter_contact_branches_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_contacts',
            name='mebel_menejer',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='main_contacts',
            name='menejer',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='main_contacts',
            name='operator',
            field=models.CharField(max_length=225),
        ),
    ]
